rock 3c: add waveshare35 support
radxa-pkg/radxa-overlays pull request #281
Opened 2024-04-01 10:52 UTC by 0101wu

rock 3c: add waveshare35 support

2024-04-02 02:28 UTC, RadxaYuntian requested changes
你这个和https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts 相比少了ads7846
另外文件名也要仿照上面的格式

2024-04-02 02:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-spi3-m1-cs0-waveshare35.dts
> +		exclusive = "GPIO4_A6","GPIO4_C6","GPIO3_C1", "GPIO3_B2", "GPIO0_C7", "GPIO4_B0", "GPIO4_B2", "GPIO4_B3";
逗号后要有空格分割元素

2024-04-02 02:28 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-spi3-m1-cs0-waveshare35.dts
> +	fragment@0 {
参照#275 使用reference格式：https://source.android.com/docs/core/architecture/dto/syntax#reference

2024-04-03 08:29 UTC, RadxaYuntian commented
ci报错，另外你这边要是改好了请点击re-request review:
![image](https://github.com/radxa-pkg/radxa-overlays/assets/95260730/b7e3993c-e55d-4ffa-83df-17c801696dd5)

2024-04-07 12:05 UTC, RadxaYuntian requested changes

2024-04-07 12:05 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3566-spi3-m1-cs0-waveshare35.dtbo
按照字母顺序排列

2024-04-07 12:05 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3566-spi3-m1-cs0-waveshare35.dts
> +	@spi3 {
看一下rk3568-spi3-m0-cs0-waveshare35.dts吧，你的格式是错误的

2024-04-08 07:27 UTC, RadxaYuntian requested changes

2024-04-08 07:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-3c-waveshare35.dtbo
不要重命名，之前的名字可以让我们之后支持其他的产品

2024-04-08 07:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +&spi3 {
```suggestion

&spi3 {	
```

2024-04-08 07:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
```suggestion
```
你SPI加个屏幕又不和HDMI冲突，为什么要关它？

2024-04-08 07:31 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
waveshare3.5的lcd和触摸分别需要spi的两个cs引脚，触摸所需要的cs引脚被hdmitxm0_cec占用，所以需要释放该引脚

2024-04-08 07:36 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
我很难想象40pin上我们复用了hdmi的引脚，请确认waveshare 3.5触摸的对应的cs引脚在我们pinout上的位置：https://docs.radxa.com/rock3/rock3c/hardware-design/hardware-interface#gpio-%E6%8E%A5%E5%8F%A3

如果对应的是一个通用的gpio,则请使用cs-gpios属性来定义：https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/spi/spi-controller.yaml#L28

2024-04-08 07:38 UTC, RadxaYuntian commented
另外别忘了本地编译overlay测试一下

2024-04-08 07:55 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
![微信图片_20240408155136](https://github.com/radxa-pkg/radxa-overlays/assets/49603174/455409c5-559f-4bda-8e2f-f4d6a6b9b018)
waveshare 3.5触摸的对应的cs引脚为SPI3_CS1_M1，即GPIO4_D1，申请该引脚的时候系统报错pin gpio4-25 already requested by fe0a000.hdmi: cannot claim for fe640000.spi

2024-04-08 07:56 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
我再去确认一遍

2024-04-08 08:08 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
我看了下原理图这里的确是复用到hdmi了。那需要在overlay里面把cec的功能关闭，而不是关闭整个hdmi:https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/boot/dts/rockchip/rk3568.dtsi#L2044

overlay只需要重新定义hdmi的pinctrl,不要包含cec的定义就好

2024-04-08 08:30 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-3c-waveshare35.dtbo
要改回原来的吗？rk3566 板子应该并不通用这个 dtbo

2024-04-08 08:31 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
好的，我把hdmi节点的status = "disabled";去掉了，测试过了，spi屏幕和hdmi都能正常使用

2024-04-08 08:42 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rock-3c-waveshare35.dtbo
先改回来吧，以后可能有别的产品也使用spi3m1

2024-04-08 08:43 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3c-waveshare35.dts
> +};
需要在description里面注明HDMI CEC功能会被关闭

2024-04-08 09:54 UTC, RadxaYuntian requested changes

2024-04-08 09:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5 inch Display on SPI3,and the CEC function of HDMI will be turned off.";
```suggestion
		description = "Enable Waveshare 3.5 inch Display on SPI3-M1.\nHDMI CEC function will be turned off when this overlay is enabled.";
```

2024-04-08 09:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		title = "Enable Waveshare 3.5 inch Display on SPI3";
```suggestion
		title = "Enable Waveshare 3.5 inch Display on SPI3-M1";
```

2024-04-08 10:20 UTC, RadxaYuntian requested changes
GitHub里面审核提出的代码修改建议可以直接在[Files changed](https://github.com/radxa-pkg/radxa-overlays/pull/281/files)里面提交。这可以帮助跟踪修改建议的状态。

---

目前没有别的建议了，可以把提交rebase合并一下，准备合并了

2024-04-08 10:21 UTC, RadxaYuntian commented
另外你要配置一下你的git config user.name和user.email，并在github上面添加你的邮箱。目前commit列表里后面的提交无法对应到你的github账号

2024-04-08 10:26 UTC, nascs commented
Zero3 和 3C 的 40-Pin 应该是一样的，可以试试 Zero3

2024-04-09 12:19 UTC, 0101wu commented
> @nascs @0101wu 有在ZERO3上测试么?

刚拿到zero3，准备测试

2024-04-16 07:19 UTC, RadxaYuntian commented
测试有结果了么？

2024-04-17 10:31 UTC, nascs commented
> 测试有结果了么？

刚在 ROCK 3C/Zero3 上面都测了一下，物理触点和屏幕实际触点有偏差，且颜色显示有问题（比如原本绿色变暗红色之类的）

2024-04-17 10:32 UTC, nascs commented
> > 测试有结果了么？
> 
> 刚在 ROCK 3C/Zero3 上面都测了一下，物理触点和屏幕实际触点有偏差，且颜色显示有问题（比如原本绿色变暗红色之类的）

@0101wu 颜色显示问题，看看是否能调一下 gamma 值？

2024-04-17 10:33 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		compatible = "radxa,rock-3c";
compatible = "radxa,rock-3c", "radxa,zero3";

2024-04-17 10:36 UTC, RadxaYuntian requested changes

2024-04-17 10:36 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		compatible = "ilitek,ili9486";
https://www.kernel.org/doc/Documentation/devicetree/bindings/display/ilitek%2Cili9486.yaml
```suggestion
		compatible = "waveshare,rpi-lcd-35, ilitek,ili9486";
```

2024-04-17 10:36 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		txbuflen = <32768>;
这里好几个属性好像驱动里没有定义：
https://www.kernel.org/doc/Documentation/devicetree/bindings/display/ilitek%2Cili9486.yaml
https://www.kernel.org/doc/Documentation/devicetree/bindings/display/panel/panel-common.yaml

2024-04-18 03:11 UTC, 0101wu commented
@nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
```
Section "InputClass"
    Identifier "calibration"
    MatchProduct "ADS7846 Touchscreen"
    Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
EndSection

```
同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
```
 Section "Device"
     Identifier  "Rockchip Graphics"
     Driver      "fbdev"
     Option      "fbdev"          "/dev/fb1"
     Option      "DRI"            "2"
 EndSection
```
如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试
参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display

2024-04-18 03:15 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		txbuflen = <32768>;
reg和spi-max-frequency应该有定义
![image](https://github.com/radxa-pkg/radxa-overlays/assets/49603174/12d1e588-435e-4af5-811c-e60a7dba668b)
txbuflen这个参数我是参考[https://github.com/radxa-pkg/radxa-overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts]加入的

2024-04-18 03:20 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		txbuflen = <32768>;
我们其他的overlay也是互相抄的，不能作为依据

2024-04-18 03:20 UTC, RadxaYuntian commented
触摸方向我们应该有[`radxa-tp-mon`](https://github.com/radxa-pkg/radxa-touchscreen-utils/blob/main/src/radxa-tp-mon)来实现自动旋转的

2024-04-18 03:33 UTC, nascs commented
> @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> 
> ```
> Section "InputClass"
>     Identifier "calibration"
>     MatchProduct "ADS7846 Touchscreen"
>     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> EndSection
> ```
> 
> 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> 
> ```
>  Section "Device"
>      Identifier  "Rockchip Graphics"
>      Driver      "fbdev"
>      Option      "fbdev"          "/dev/fb1"
>      Option      "DRI"            "2"
>  EndSection
> ```
> 
> 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display

加了 99-touchscreen-calibration.conf 配置后，触摸正常

2024-04-18 03:37 UTC, nascs commented
> > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > ```
> > Section "InputClass"
> >     Identifier "calibration"
> >     MatchProduct "ADS7846 Touchscreen"
> >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > EndSection
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > ```
> >  Section "Device"
> >      Identifier  "Rockchip Graphics"
> >      Driver      "fbdev"
> >      Option      "fbdev"          "/dev/fb1"
> >      Option      "DRI"            "2"
> >  EndSection
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> 
> 加了 99-touchscreen-calibration.conf 配置后，触摸正常

但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是

2024-04-18 06:46 UTC, 0101wu commented
> > > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > > ```
> > > Section "InputClass"
> > >     Identifier "calibration"
> > >     MatchProduct "ADS7846 Touchscreen"
> > >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > > EndSection
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > > ```
> > >  Section "Device"
> > >      Identifier  "Rockchip Graphics"
> > >      Driver      "fbdev"
> > >      Option      "fbdev"          "/dev/fb1"
> > >      Option      "DRI"            "2"
> > >  EndSection
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> > 
> > 
> > 加了 99-touchscreen-calibration.conf 配置后，触摸正常
> 
> 但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是

是否有替换20-modesetting.conf呢？这是我的测试结果
![55c89768f8120eec94726a9142b0e84](https://github.com/radxa-pkg/radxa-overlays/assets/49603174/ea68c183-6c84-4741-bca4-abb2282d4928)

2024-04-18 06:58 UTC, nascs commented
> > > > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > > > ```
> > > > Section "InputClass"
> > > >     Identifier "calibration"
> > > >     MatchProduct "ADS7846 Touchscreen"
> > > >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > > > EndSection
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > > > ```
> > > >  Section "Device"
> > > >      Identifier  "Rockchip Graphics"
> > > >      Driver      "fbdev"
> > > >      Option      "fbdev"          "/dev/fb1"
> > > >      Option      "DRI"            "2"
> > > >  EndSection
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> > > 
> > > 
> > > 加了 99-touchscreen-calibration.conf 配置后，触摸正常
> > 
> > 
> > 但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是
> 
> 是否有替换20-modesetting.conf呢？这是我的测试结果 ![55c89768f8120eec94726a9142b0e84](https://private-user-images.githubusercontent.com/49603174/323495381-ea68c183-6c84-4741-bca4-abb2282d4928.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjMwODMsIm5iZiI6MTcxMzQyMjc4MywicGF0aCI6Ii80OTYwMzE3NC8zMjM0OTUzODEtZWE2OGMxODMtNmM4NC00NzQxLWJjYTQtYWJiMjI4MmQ0OTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjA5MThiMmJiZGNjMzdlZmQ1Y2M4YzJjZDJhZmQ3MTY4NGVkZTlkMTE4ODQ0YTU3ZTkyMzJkOTIwYWY1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNg6IGTDlnc_oX4yWSK4aGHCzuY1h8jXF8Sl2WG-cc8)

替换过了
![waveshare-spi-lcd](https://github.com/radxa-pkg/radxa-overlays/assets/105425502/a6520131-5c47-425b-9955-ad45379e75c7)
这个原来的背景色是黑色为主

2024-04-18 07:05 UTC, nascs commented
> > > > > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > > > > ```
> > > > > Section "InputClass"
> > > > >     Identifier "calibration"
> > > > >     MatchProduct "ADS7846 Touchscreen"
> > > > >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > > > > EndSection
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > > > > ```
> > > > >  Section "Device"
> > > > >      Identifier  "Rockchip Graphics"
> > > > >      Driver      "fbdev"
> > > > >      Option      "fbdev"          "/dev/fb1"
> > > > >      Option      "DRI"            "2"
> > > > >  EndSection
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> > > > 
> > > > 
> > > > 加了 99-touchscreen-calibration.conf 配置后，触摸正常
> > > 
> > > 
> > > 但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是
> > 
> > 
> > 是否有替换20-modesetting.conf呢？这是我的测试结果 ![55c89768f8120eec94726a9142b0e84](https://private-user-images.githubusercontent.com/49603174/323495381-ea68c183-6c84-4741-bca4-abb2282d4928.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjMwODMsIm5iZiI6MTcxMzQyMjc4MywicGF0aCI6Ii80OTYwMzE3NC8zMjM0OTUzODEtZWE2OGMxODMtNmM4NC00NzQxLWJjYTQtYWJiMjI4MmQ0OTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjA5MThiMmJiZGNjMzdlZmQ1Y2M4YzJjZDJhZmQ3MTY4NGVkZTlkMTE4ODQ0YTU3ZTkyMzJkOTIwYWY1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNg6IGTDlnc_oX4yWSK4aGHCzuY1h8jXF8Sl2WG-cc8)
> 
> 替换过了 ![waveshare-spi-lcd](https://private-user-images.githubusercontent.com/105425502/323498328-a6520131-5c47-425b-9955-ad45379e75c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjM4MDEsIm5iZiI6MTcxMzQyMzUwMSwicGF0aCI6Ii8xMDU0MjU1MDIvMzIzNDk4MzI4LWE2NTIwMTMxLTVjNDctNDI1Yi05OTU1LWFkNDUzNzllNzVjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNjU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2MjcxMzM0YTM0ZmI5ZDE3NjhkZDFkNjU1MjdhZWZlYTMxMGQ2MjExZTVkNjEzOWExNWI2YTNkYjU0NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6WUVQe-D_kYqNWFogAgOXPdXWrKYBbzlikH3d1hK_Q) 这个原来的背景色是黑色为主

![lcd](https://github.com/radxa-pkg/radxa-overlays/assets/105425502/a83a2022-6a87-46df-a585-f4bec29a33c4)

这是开机启动画面，一般正常的话是黑色背景的

2024-04-18 07:09 UTC, 0101wu commented
> > > > > > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > > > > > ```
> > > > > > Section "InputClass"
> > > > > >     Identifier "calibration"
> > > > > >     MatchProduct "ADS7846 Touchscreen"
> > > > > >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > > > > > EndSection
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > > > > > ```
> > > > > >  Section "Device"
> > > > > >      Identifier  "Rockchip Graphics"
> > > > > >      Driver      "fbdev"
> > > > > >      Option      "fbdev"          "/dev/fb1"
> > > > > >      Option      "DRI"            "2"
> > > > > >  EndSection
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> > > > > 
> > > > > 
> > > > > 加了 99-touchscreen-calibration.conf 配置后，触摸正常
> > > > 
> > > > 
> > > > 但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是
> > > 
> > > 
> > > 是否有替换20-modesetting.conf呢？这是我的测试结果 ![55c89768f8120eec94726a9142b0e84](https://private-user-images.githubusercontent.com/49603174/323495381-ea68c183-6c84-4741-bca4-abb2282d4928.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjMwODMsIm5iZiI6MTcxMzQyMjc4MywicGF0aCI6Ii80OTYwMzE3NC8zMjM0OTUzODEtZWE2OGMxODMtNmM4NC00NzQxLWJjYTQtYWJiMjI4MmQ0OTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjA5MThiMmJiZGNjMzdlZmQ1Y2M4YzJjZDJhZmQ3MTY4NGVkZTlkMTE4ODQ0YTU3ZTkyMzJkOTIwYWY1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNg6IGTDlnc_oX4yWSK4aGHCzuY1h8jXF8Sl2WG-cc8)
> > 
> > 
> > 替换过了 ![waveshare-spi-lcd](https://private-user-images.githubusercontent.com/105425502/323498328-a6520131-5c47-425b-9955-ad45379e75c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjM4MDEsIm5iZiI6MTcxMzQyMzUwMSwicGF0aCI6Ii8xMDU0MjU1MDIvMzIzNDk4MzI4LWE2NTIwMTMxLTVjNDctNDI1Yi05OTU1LWFkNDUzNzllNzVjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNjU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2MjcxMzM0YTM0ZmI5ZDE3NjhkZDFkNjU1MjdhZWZlYTMxMGQ2MjExZTVkNjEzOWExNWI2YTNkYjU0NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6WUVQe-D_kYqNWFogAgOXPdXWrKYBbzlikH3d1hK_Q) 这个原来的背景色是黑色为主
> 
> ![lcd](https://private-user-images.githubusercontent.com/105425502/323500296-a83a2022-6a87-46df-a585-f4bec29a33c4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQyNTMsIm5iZiI6MTcxMzQyMzk1MywicGF0aCI6Ii8xMDU0MjU1MDIvMzIzNTAwMjk2LWE4M2EyMDIyLTZhODctNDZkZi1hNTg1LWY0YmVjMjlhMzNjNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmYyMDE0ZTg3YjQ4MDUyMmU0MTVlNDk2OGZkZTAzZmZmNGVkNWYxOWZmNTIzYWQxNTgxODNhNTgxZmVjMjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pTgNf_S6e9xZ_A0rD2NSX0EIVQUINYw7lhATTtssQXo)
> 
> 这是开机启动画面，一般正常的话是黑色背景的

请问下你那边有没有备用屏幕测测看，有可能是屏幕硬件问题
![df4fdd146a2c8605a451c6486307b89](https://github.com/radxa-pkg/radxa-overlays/assets/49603174/d3c3b04c-2edf-4cff-a241-015dc7366634)

2024-04-18 07:31 UTC, nascs commented
> > > > > > > @nascs 默认情况下，x轴的触摸方向与显示方向相反，需在/etc/X11/xorg.conf.d下添加一个配置文件99-touchscreen-calibration.conf，内容为：
> > > > > > > ```
> > > > > > > Section "InputClass"
> > > > > > >     Identifier "calibration"
> > > > > > >     MatchProduct "ADS7846 Touchscreen"
> > > > > > >     Option "TransformationMatrix" "-1 0 1 0 1 0 0 0 1"
> > > > > > > EndSection
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 同时将/etc/X11/xorg.conf.d/20-modesetting.conf备份并替换为以下配置：
> > > > > > > ```
> > > > > > >  Section "Device"
> > > > > > >      Identifier  "Rockchip Graphics"
> > > > > > >      Driver      "fbdev"
> > > > > > >      Option      "fbdev"          "/dev/fb1"
> > > > > > >      Option      "DRI"            "2"
> > > > > > >  EndSection
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 如果同时插入hdmi，则是/dev/fb1，如果不插入hdmi，则是/dev/fb0，我这边按这两个配置后暂时没有色彩不准确的问题，麻烦你再试试 参考https://docs.radxa.com/en/accessories/peripherals/waveshare-35-display
> > > > > > 
> > > > > > 
> > > > > > 加了 99-touchscreen-calibration.conf 配置后，触摸正常
> > > > > 
> > > > > 
> > > > > 但是我这边色彩确实有问题, ROCK 3C 和 Zero3 都是
> > > > 
> > > > 
> > > > 是否有替换20-modesetting.conf呢？这是我的测试结果 ![55c89768f8120eec94726a9142b0e84](https://private-user-images.githubusercontent.com/49603174/323495381-ea68c183-6c84-4741-bca4-abb2282d4928.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjMwODMsIm5iZiI6MTcxMzQyMjc4MywicGF0aCI6Ii80OTYwMzE3NC8zMjM0OTUzODEtZWE2OGMxODMtNmM4NC00NzQxLWJjYTQtYWJiMjI4MmQ0OTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjA5MThiMmJiZGNjMzdlZmQ1Y2M4YzJjZDJhZmQ3MTY4NGVkZTlkMTE4ODQ0YTU3ZTkyMzJkOTIwYWY1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNg6IGTDlnc_oX4yWSK4aGHCzuY1h8jXF8Sl2WG-cc8)
> > > 
> > > 
> > > 替换过了 ![waveshare-spi-lcd](https://private-user-images.githubusercontent.com/105425502/323498328-a6520131-5c47-425b-9955-ad45379e75c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjM4MDEsIm5iZiI6MTcxMzQyMzUwMSwicGF0aCI6Ii8xMDU0MjU1MDIvMzIzNDk4MzI4LWE2NTIwMTMxLTVjNDctNDI1Yi05OTU1LWFkNDUzNzllNzVjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNjU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjc2MjcxMzM0YTM0ZmI5ZDE3NjhkZDFkNjU1MjdhZWZlYTMxMGQ2MjExZTVkNjEzOWExNWI2YTNkYjU0NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q6WUVQe-D_kYqNWFogAgOXPdXWrKYBbzlikH3d1hK_Q) 这个原来的背景色是黑色为主
> > 
> > 
> > ![lcd](https://private-user-images.githubusercontent.com/105425502/323500296-a83a2022-6a87-46df-a585-f4bec29a33c4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQyNTMsIm5iZiI6MTcxMzQyMzk1MywicGF0aCI6Ii8xMDU0MjU1MDIvMzIzNTAwMjk2LWE4M2EyMDIyLTZhODctNDZkZi1hNTg1LWY0YmVjMjlhMzNjNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwNzA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmYyMDE0ZTg3YjQ4MDUyMmU0MTVlNDk2OGZkZTAzZmZmNGVkNWYxOWZmNTIzYWQxNTgxODNhNTgxZmVjMjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pTgNf_S6e9xZ_A0rD2NSX0EIVQUINYw7lhATTtssQXo)
> > 这是开机启动画面，一般正常的话是黑色背景的
> 
> 请问下你那边有没有备用屏幕测测看，有可能是屏幕硬件问题 ![df4fdd146a2c8605a451c6486307b89](https://private-user-images.githubusercontent.com/49603174/323501920-d3c3b04c-2edf-4cff-a241-015dc7366634.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQ1MDIsIm5iZiI6MTcxMzQyNDIwMiwicGF0aCI6Ii80OTYwMzE3NC8zMjM1MDE5MjAtZDNjM2IwNGMtMmVkZi00Y2ZmLWEyNDEtMDE1ZGM3MzY2NjM0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzZjMmI2ZmJmODA4MGMzNzkzNjM2OGQ0MjcxMWEyZjY0YzVlNjY2NTUzZWZhYzk5NzAwMzE5NmViOGRhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EWhjYGEkdXk7lOg28dpOScWkIB6lOiz-51Jx4zLL_D8)

屏幕应该是没问题的，刚买回来不久，也换了一块试了一下，效果一样

2024-04-18 09:31 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		debug = <0>;
debug = <0>;
		init = <0x10000b0 0x0
				0x1000011
				0x20000ff
				0x1000021
				0x100003a 0x55
				0x10000c2 0x33
				0x10000c5 0x0 0x1e 0x80
				0x1000036 0x28
				0x10000b1 0xb0
				0x10000e0 0x0 0x13 0x18 0x4 0xf 0x6 0x3a 0x56 0x4d 0x3 0xa 0x6 0x30 0x3e 0xf
				0x10000e1 0x0 0x13 0x18 0x1 0x11 0x6 0x38 0x34 0x4d 0x6 0xd 0xb 0x31 0x37 0xf 
				0x1000011
				0x20000ff
				0x1000029>;


你看一下加一下这个 init， 看看你那边是否会有影响？加了这个 init 序列号之后，我这边现在颜色显示是正常的了。

2024-04-18 09:46 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		txbuflen = <32768>;
> reg和spi-max-frequency应该有定义 ![image](https://private-user-images.githubusercontent.com/49603174/323453318-12d1e588-435e-4af5-811c-e60a7dba668b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzI5MzcsIm5iZiI6MTcxMzQzMjYzNywicGF0aCI6Ii80OTYwMzE3NC8zMjM0NTMzMTgtMTJkMWU1ODgtNDM1ZS00YWY1LTgxMWMtZTYwYTdkYmE2NjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MzAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmYjNjODljZGRhMGZkYWU4YTlhYjJkMDA5NGU1ODFkMGRlOWM4MDQ5NjliZTAxNTUyYjMzOTg1ZDQ2ZGE1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_O0DNNO1ym0XMGWLVWkn47uRTlYsTsnUBhXgDV2qNY) txbuflen这个参数我是参考[https://github.com/radxa-pkg/radxa-overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts]加入的

[txbuflen](https://github.com/torvalds/linux/blob/8cd26fd90c1ad7acdcfb9f69ca99d13aa7b24561/drivers/staging/fbtft/fbtft-core.c#L513) 有定义的

2024-04-18 09:48 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		debug = <0>;
> ```
> 	debug = <0>;
> 	init = <0x10000b0 0x0
> 			0x1000011
> 			0x20000ff
> 			0x1000021
> 			0x100003a 0x55
> 			0x10000c2 0x33
> 			0x10000c5 0x0 0x1e 0x80
> 			0x1000036 0x28
> 			0x10000b1 0xb0
> 			0x10000e0 0x0 0x13 0x18 0x4 0xf 0x6 0x3a 0x56 0x4d 0x3 0xa 0x6 0x30 0x3e 0xf
> 			0x10000e1 0x0 0x13 0x18 0x1 0x11 0x6 0x38 0x34 0x4d 0x6 0xd 0xb 0x31 0x37 0xf 
> 			0x1000011
> 			0x20000ff
> 			0x1000029>;
> ```
> 
> 你看一下加一下这个 init， 看看你那边是否会有影响？加了这个 init 序列号之后，我这边现在颜色显示是正常的了。

![color_lcd](https://github.com/radxa-pkg/radxa-overlays/assets/105425502/7e89d7db-8444-4b46-9252-fbedcb28a364)

2024-04-18 09:58 UTC, RadxaYuntian commented
你们对比一下你们的硬件版本吧

2024-04-18 10:25 UTC, nascs commented
> 你们对比一下你们的硬件版本吧

ROCK 3C V1.2/V1.3 都试过了， Zero3 X1.1，加了 init 之后是正常的颜色，没加是反色（即黑白对调）。
[init_sequence](https://github.com/torvalds/linux/blob/8cd26fd90c1ad7acdcfb9f69ca99d13aa7b24561/drivers/staging/fbtft/fbtft-core.c#L517) 也是有定义的，看驱动，它应该也是需要传一个初始化的序列号进去的，不然使用默认的序列号多少是会有颜色的偏差的。

2024-04-18 10:39 UTC, RadxaYuntian commented
我是说你们屏幕的硬件版本。

2024-04-18 10:45 UTC, nascs commented
> 我是说你们屏幕的硬件版本。

我这个屏幕是 Waveshare RPI LCD (B) Rev 2.0, 他的屏幕应该是 allnet 的，之前那块，用的 IC 是一样的

2024-04-18 10:52 UTC, nascs commented
> > 我是说你们屏幕的硬件版本。
> 
> 我这个屏幕是 Waveshare RPI LCD (B) Rev 2.0, 他的屏幕应该是 allnet 的，之前那块，用的 IC 是一样的

另外我之前用他的那块屏，年前也试过 3C，也有遇到过反色的情况。

2024-04-18 14:05 UTC, 0101wu commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		debug = <0>;
加了这个init，我这边屏幕点不亮，因为我这块屏幕是Waveshare 3.5inch RPI LCD（C），应该序列号不一致

2024-04-18 14:06 UTC, 0101wu commented
> > 我是说你们屏幕的硬件版本。
> 
> 我这个屏幕是 Waveshare RPI LCD (B) Rev 2.0, 他的屏幕应该是 allnet 的，之前那块，用的 IC 是一样的

我这块屏幕是Waveshare 3.5inch RPI LCD（C）

2024-04-19 02:06 UTC, RadxaYuntian commented
不同的硬件版本要提供不同的overlay。waveshare自己也给ABC提供了不同的配置脚本

2024-04-19 02:21 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		debug = <0>;
> 加了这个init，我这边屏幕点不亮，因为我这块屏幕是Waveshare 3.5inch RPI LCD（C），应该序列号不一致

行，后面我加一个 model C 的

2024-04-19 02:23 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		debug = <0>;
要修改这个overlay的title和description,另外看看其他现有的是不是也是给C做的，同步更新

2024-04-19 02:36 UTC, nascs commented
現在的 overlay 格式，我感觉后面有时间，可以把 waveshare spi lcd 的 Overlay 写成一个 dtsi，然後 include dtsi 之後，就不用寫這麼多重複代碼了，改改 spi/主要的 幾個引腳/序列號 就好。

2024-04-19 02:58 UTC, RadxaYuntian commented
[你们愿意这么做就行](https://github.com/radxa-pkg/radxa-overlays/commit/698a1e12713f4896e3c1386956fefec09f1762f0#diff-0982110b806e866f099b5ab59bac5b12d81f812990a856772094a37d2567499dL4-R5)……

2024-04-19 08:53 UTC, RadxaYuntian requested changes

2024-04-19 08:53 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		title = "Enable Waveshare 3.5 inch Display Modle (C) on SPI3-M1";
```suggestion
		title = "Enable Waveshare 3.5inch RPi LCD (C) on SPI3-M1";
```
用他们正确的产品名吧

2024-04-19 08:53 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5 inch Display Modle (C) on SPI3-M1.\nHDMI CEC function will be turned off when this overlay is enabled.";
```suggestion
		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI3-M1.\nHDMI CEC function will be turned off when this overlay is enabled.";
```

2024-04-23 03:51 UTC, RadxaYuntian commented
@0101wu 看一下

2024-04-23 03:59 UTC, RadxaYuntian requested changes
commit合并一下

2024-04-23 06:16 UTC, RadxaYuntian approved these changes

2024-04-23 06:18 UTC, merged