rock 2a: add eeprom support on i2c1-m0
radxa-pkg/radxa-overlays pull request #287
Opened 2024-04-03 11:09 UTC by lsj123lsjlsj

rock 2a: add eeprom support on i2c1-m0

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-04-03 11:30 UTC, RadxaYuntian requested changes

2024-04-03 11:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +dtb-$(CONFIG_CPU_RK3528) += \
这里仅限于必须使用rockchip内核独有头文件的overlay。你的overlay没有用到rockchip内核头文件，不要放在这里

2024-04-03 11:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +};
缺少结尾空行

2024-04-03 11:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +		title = "Enable EEPPOOM on I2C1-M0";
这个EEPROM是板载的么？是的话要在板级设备树里打开

2024-04-03 11:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +		description = "Enable eeprom on I2C1-M0.";
缺少exclusive

2024-04-08 01:45 UTC, lsj123lsjlsj commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +		description = "Enable eeprom on I2C1-M0.";
EEPROM是板载的，但是Stephen说做成overlay

2024-04-08 07:23 UTC, RadxaYuntian requested changes

2024-04-08 07:23 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +		description = "Enable eeprom on I2C1-M0.";
```suggestion
		description = "Enable EEPROM on I2C1-M0.\nThis is a onboard device that we disable by default, so GPIO pins can function as expected.";
```

2024-04-08 07:23 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
> +		title = "Enable EEPPOOM on I2C1-M0";
```suggestion
		title = "Enable EEPROM on I2C1-M0";
```

2024-04-08 07:38 UTC, RadxaYuntian requested changes
rebase

2024-04-08 08:10 UTC, RadxaYuntian approved these changes

2024-04-08 08:10 UTC, merged