rock 2a: add tve support and close hdmi
radxa-pkg/radxa-overlays pull request #289
Opened 2024-04-08 08:28 UTC by lsj123lsjlsj

rock 2a: add tve support and close hdmi

Signed-off-by: SongJun Li <lisongjun@radxa.com>

2024-04-08 09:15 UTC, RadxaYuntian requested changes

2024-04-08 09:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +		title = "Enable TVE and disable HDMI";
```suggestion
		title = "Enable analog video output";
```

2024-04-08 09:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +		compatible = "radxa,rock-2a", "rockchip,rk3528";
```suggestion
		compatible = "radxa,rock-2a";
```
如果加上soc则会匹配所有rk3528设备：https://github.com/radxa-pkg/radxa-overlays?tab=readme-ov-file#c-compatible-array

2024-04-08 09:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +		exclusive = "VDAC";
```suggestion
		exclusive = "tve";
```
exclusive仅限GPIO编号或设备树里面的label：https://github.com/radxa-pkg/radxa-overlays?tab=readme-ov-file#e-exclusive-array

2024-04-08 09:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +		description = "Enable TVE and disable HDMI.";
```suggestion
		description = "Enable analog video output.";
```

2024-04-08 09:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +};
我看 https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/boot/dts/rockchip/rk3528-evb.dtsi#L301-L307 里面两个都可以同时开启啊？而且这里的开机画面显示也是同时route到两个地方： https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr4.1/arch/arm64/boot/dts/rockchip/rk3528-linux.dtsi#L67-L81

2024-04-09 10:21 UTC, RadxaStephen commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +};
先弄单显，后面再加一个双显。

2024-04-09 10:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +};
这个有必要么？用户不需要hdmi可以不用啊

2024-04-09 10:47 UTC, RadxaStephen commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +};
现在双显时，hdmi 显示会出现界面排版错乱。

2024-04-09 10:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve-disable-hdmi.dts
> +};
@lsj123lsjlsj 那先还是只做单显，但文件名和title不要说disable HDMI，等我们之后修复后直接更新这个overlay就好

2024-04-09 11:45 UTC, RadxaYuntian requested changes

2024-04-09 11:45 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve.dts
> +		description = "Enable analog video output.";
```suggestion
		description = "Enable analog video output.\nCurrently this overlay will disable HDMI output due to display artifacts.";
```

2024-04-09 11:51 UTC, RadxaYuntian requested changes
rebase

2024-04-09 12:10 UTC, merged