Waveshare lcd dtsi
radxa-pkg/radxa-overlays pull request #303
Opened 2024-04-24 07:35 UTC by nascs

将 ili9486 和 ads7846 抽出来模块化

2024-04-24 07:37 UTC, nascs commented
> 将 ili9486 和 ads7846 抽出来模块化

这种语法应该是合法的。

https://github.com/torvalds/linux/blob/9d1ddab261f3e2af7c384dc02238784ce0cf9f98/arch/arm/boot/dts/aspeed/aspeed-bmc-amd-ethanolx.dts#L63C13-L63C38

https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/aspeed/openbmc-flash-layout.dtsi

2024-04-24 08:10 UTC, RadxaYuntian requested changes
waveshare35-lcd.dtsi:
```
#ifndef DISPLAY_SPI
  #error "DISPLAY_SPI is undefined."
#endif

&DISPLAY_SPI {
  ili9486@0 {
    ...
  };
};
```
rk1234.dts:
```
#define DISPLAY_SPI spi1
#include "waveshare35-lcd.dtsi"

&DISPLAY_SPI {
 ...
};
```

2024-04-25 08:22 UTC, RadxaYuntian requested changes

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	metadata {
要说明这个overlay支持的Model,参考我们之前那个PR的格式

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	#address-cells = <1>;
status, #address-cells, #size-cells都应该可以放到dtsi

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
>  	metadata {
title更新

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
>  	max-freq = <16000000>;
这个字段应该是错的吧

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
> +		dc-gpios = <&gpio3 RK_PB2 GPIO_ACTIVE_HIGH>;
这个每个产品都不同，就不要定义
```suggestion
```

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
> +		pendown-gpio = <&gpio3 RK_PA1 GPIO_ACTIVE_HIGH>;
```suggestion
```

2024-04-25 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
> +	vcc-supply = <&vcc5v0_sys>;
```suggestion
```
这个dtsi里面不是定义了么

2024-04-25 08:23 UTC, RadxaYuntian commented
还有这个CI不是全红了么？你没有收到邮件通知？

2024-04-25 08:51 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	metadata {
ROCK 4 的 pin 26 是 adc, Model B 的屏幕触摸引脚刚好是 pin 26, 所以 ROCK 4 + Model B 屏幕，是无法触屏的， Model C 触摸是好的

2024-04-25 09:06 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
>  	max-freq = <16000000>;
https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/spi/spi-controller.yaml

2024-04-25 09:09 UTC, RadxaYuntian requested changes

2024-04-25 09:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	metadata {
overlay加上，然后说明触摸不可以用就好。

2024-04-25 09:40 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	metadata {
另外这两个屏在 rk3588 上触摸都还有问题，rk356x 上没问题，zero3 和 rock 3c 的触摸都是好的

2024-04-25 10:38 UTC, RadxaYuntian requested changes

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
>  	max-freq = <48000000>;
这个属性不仅是错的，还只在spi device里面才存在：https://github.com/torvalds/linux/blob/v5.10/Documentation/devicetree/bindings/spi/spi-controller.yaml#L120

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +		title = "Enable Waveshare 3.5inch RPi LCD (B) on SPI1";
```suggestion
		title = "Enable Waveshare 3.5inch RPi LCD (B) on SPI1 (No Touch Support)";
```

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (B) on SPI1.\nTouch is not supported in hardware.";
```suggestion
		description = "Enable Waveshare 3.5inch RPi LCD (B) on SPI1 (No Touch Support).\nDue to hardware conflict, touch is not available when using with ROCK 4.";
```

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts
> +	spi-max-frequency = <15000000>;
有的overlay定义了这个有的没有定义，是不是统一移动到dtsi？

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +};
```suggestion
};

&ads7846 {
	status = "disabled";
};
```

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
> +&hdmi {
hdmi放最后吧，这样我们waveshare的overlay前面部分的结构都比较类似

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35b.dts
> +&ili9486 {
重复定义
缩进不对

2024-04-25 10:38 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
看看MRAA/wiringX那些头文件都有个避免2次引用的ifdef把全文都包括进去。我们这里也加上吧

2024-04-25 11:50 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
>  	max-freq = <16000000>;
> SPI controller应该没有max-freq这个属性

这完了，得再提个 pr 把这属性全删了

2024-04-25 11:54 UTC, RadxaYuntian requested changes

2024-04-25 11:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +#include "waveshare35-lcd.dtsi"
```suggestion
#include "rk3399-spi1-waveshare35.dts"
```
应该可以在这里引用上面的文件

2024-04-25 11:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +		category = "misc";
```suggestion
```
相同定义可以省去

2024-04-25 11:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +		exclusive = "GPIO1_B0", "GPIO1_A7", "GPIO1_B1", "GPIO1_B2", "GPIO4_D2", "GPIO4_D4", "GPIO4_D5" ;
这里没了触摸，可以删掉相关GPIO

2024-04-25 11:54 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +
```suggestion
```
重复定义就可以删掉了

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
> +#ifdef DISPLAY_SPI
```suggestion
#ifndef __WAVESHARE35_LCD_DTSI__
#define __WAVESHARE35_LCD_DTSI__

#include <dt-bindings/gpio/gpio.h>
#include <dt-bindings/pinctrl/rockchip.h>
#include <dt-bindings/interrupt-controller/irq.h>

#ifndef DISPLAY_SPI
#error "DISPLAY_SPI is undefined."
#endif
```

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
> +#endif
```suggestion
#endif // __WAVESHARE35_LCD_DTSI__
```

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35b.dts
> +	pinctrl-0 = <&spi1_clk &spi1_rx &spi1_tx>;
这两个跟“rk3399-spi1-waveshare35.dts”里是一样的，反而是num-cs和cs-gpios要重新定义，删掉触摸用的cs吧？

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35b.dts
> +		exclusive = "GPIO4_A6", "GPIO4_C6", "GPIO3_C1", "GPIO3_B2", "GPIO3_A1", "GPIO4_D1", "GPIO4_B2", "GPIO4_B3";
```suggestion
```
这跟C的不是一样的么？

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35b.dts
> +#include "waveshare35-lcd.dtsi"
```suggestion
#include "rk3588-spi0-m1-cs0-waveshare35.dts"
```
自己检查一下啊

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI0-M0.\nTouch is temporarily unavailable.";
怎么触摸又不能用了呢？

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35b.dts
> +		exclusive = "GPIO1_B1", "GPIO1_D5", "GPIO4_A0", "GPIO4_A1", "GPIO4_A2", "GPIO4_A6", "GPIO4_B2" ;
这不是跟上面一样的么？
```suggestion
```

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35b.dts
> +		description = "Enable Waveshare 3.5 inch Display (B) on SPI0-M0.\nTouch is temporarily unavailable.";
触摸？

2024-04-26 06:50 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35b.dts
> +		description = "Enable Waveshare 3.5 inch Display (B) on SPI0-M0.\nTouch is temporarily unavailable.";
触摸？

2024-04-26 06:52 UTC, RadxaYuntian requested changes

2024-04-26 06:52 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts
>  	metadata {
这个title和description按照我们现在的格式更新

2024-04-26 07:18 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI0-M0.\nTouch is temporarily unavailable.";
> 怎么触摸又不能用了呢？

昨天提到过，这两个屏幕在 RK3588 系列都还有触摸问题

2024-04-26 07:26 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI0-M0.\nTouch is temporarily unavailable.";
gpio定义先保留，但status可以先disabled掉
另外description抄上面审核过的句子

2024-04-26 07:41 UTC, RadxaYuntian requested changes

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts
应该有对应的[rk3568-spi3-m0-cs0-waveshare35.dts](https://github.com/radxa-pkg/radxa-overlays/pull/303/files#diff-16bd9b538fb153ed0e4a63f5815d0f0e8e354cfd22ea4a05e471ebf3881c90de)吧？把这个文件也更新了

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
>  		reset-gpios = <&gpio3 RK_PC1 GPIO_ACTIVE_LOW>;
缩进不催

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35b.dts
> +
```suggestion
```
include文件已包含

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI0-M0.\nTouch is temporarily unavailable.";
description没有更新

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35b.dts
> +
```suggestion
```

2024-04-26 07:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
>  /plugin/;
这两行其实也可以移到dtsi里面

2024-04-26 07:50 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts
>  		reset-gpios = <&gpio3 RK_PC1 GPIO_ACTIVE_LOW>;
> 缩进不催

emm，这里没看出来

2024-04-26 08:08 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts
rk356x 的触摸都是可以的

2024-04-26 08:22 UTC, RadxaYuntian requested changes

2024-04-26 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/waveshare35-lcd.dtsi
> +#endif
```suggestion
#ifndef DISPLAY_SPI
#error "DISPLAY_SPI is undefined."
#endif

/dts-v1/;
/plugin/;

#include <dt-bindings/gpio/gpio.h>
#include <dt-bindings/pinctrl/rockchip.h>
#include <dt-bindings/interrupt-controller/irq.h>
```
先检查是否合法，再加入boilerplate代码，最后是我们真正的头文件

2024-04-26 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts
说错，我是指rk3568-spi3-m0-cs0-waveshare35**b**.dts

2024-04-26 08:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
> +		description = "Enable Waveshare 3.5inch RPi LCD (C) on SPI0-M0.\nTouch is temporarily unavailable.";
算了，就这样吧

2024-04-26 08:24 UTC, RadxaYuntian reviewed
重写一下提交历史吧

2024-04-26 08:41 UTC, RadxaYuntian approved these changes

2024-04-26 08:42 UTC, merged