arm64: overlays: Add overlay description for rock 5c
radxa-pkg/radxa-overlays pull request #310
Opened 2024-05-06 03:18 UTC by vamrs-feng

2024-05-06 08:41 UTC, RadxaYuntian requested changes

2024-05-06 08:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-fiq-debugger-uart6m1.dts
> +On Radxa ROCK 5C this is TX pin 19 and RX pin 21.";
重复`";`，估计就是因为这个导致编译报错
你这边修改的时候遇到了结尾的`";`就把它新起一行放着吧，免得后续添加又出现这种问题

2024-05-08 03:25 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm14-m1.dts
> +On Radxa CM5 RPI CM4 IO this is pin 32.";
```suggestion
On Radxa CM5 RPI CM4 IO this is pin 32.
";
```
原本就另起一行的不要改掉

2024-05-08 03:25 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm15-m3.dts
> +		On Radxa ROCK 5A this is pin 3.
不要缩进，编译器不会删掉前面的空格

2024-05-08 03:25 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm15-m3.dts
> +		On Radxa ROCK 5A this is pin 3.
不要缩进，编译器不会删掉前面的空格

2024-05-08 03:27 UTC, RadxaYuntian requested changes

2024-05-08 03:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm7-m0.dts
> +On Radxa CM5 RPI CM4 IO this is pin 3.";
```suggestion
On Radxa CM5 RPI CM4 IO this is pin 3.
";
```

2024-05-08 03:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts
> +		On Radxa ROCK 5A this is TX pin 8 & RX pin 10.
缩进

2024-05-08 03:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
> +		On Radxa ROCK 5A this is CTSN pin 24, RTSN pin 23, TX pin 19, and RX pin 21.
缩进

2024-05-08 03:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
>  		category = "misc";
这个overlay现在都是禁用的，检查一下5a和5c到底能否支持

2024-05-08 03:27 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
>  		category = "misc";
overlay禁用

2024-05-11 02:16 UTC, RadxaYuntian requested changes

2024-05-11 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-can1-m1.dts
> +On Radxa ROCK 5C this is RX pin 13 & TX pin 11.";
```suggestion
On Radxa ROCK 5C this is RX pin 13 & TX pin 11.
";
```
原本就是单独一行的就别改了

2024-05-11 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c4-m3.dts
> -On Radxa ROCK 5A this is SDA pin 31 and SCL pin 29.
这个应该是5B+吧？只是写错了

2024-05-11 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm14-m1.dts
> +On Radxa CM5 RPI CM4 IO this is pin 32.";
原本就另起一行的不要改掉
怎么还能自己mark as resolved？

2024-05-11 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
>  		category = "misc";
这个overlay现在都是禁用的，检查一下5a和5c到底能否支持

2024-05-11 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
>  		category = "misc";
overlay禁用

2024-05-11 10:06 UTC, vamrs-feng commented
重新整理了一下

2024-05-11 10:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c4-m3.dts
> -On Radxa ROCK 5A this is SDA pin 31 and SCL pin 29.
所以还是没有解决5B+的描述不见了的问题

2024-05-11 10:10 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart6-m1-full.dts
>  		category = "misc";
还是没有澄清是否支持

2024-05-11 10:10 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-uart8-m0-full.dts
>  		category = "misc";
还是没有澄清是否支持

2024-05-13 06:47 UTC, RadxaYuntian requested changes
squash一下提交吧

2024-05-13 11:31 UTC, RadxaYuntian approved these changes

2024-05-13 11:33 UTC, merged