fix: can overlays aren't compiled when kernel is bsp 6.1
radxa-pkg/radxa-overlays pull request #322
Opened 2024-05-20 11:22 UTC by CodeChenL

* closes https://github.com/radxa-pkg/radxa-overlays/issues/316

2024-05-20 11:33 UTC, RadxaYuntian requested changes

2024-05-20 11:33 UTC, RadxaYuntian commented on .github/workflows/build.yml
> +              if ! grep "$OVERLAY_NAME" "${OVERLAY_PATH}/Makefile" >/dev/null 2>/dev/null && ! grep "$OVERLAY_NAME" "${OVERLAY_PATH}"/*.mak >/dev/null 2>/dev/null;
`Usage: grep [OPTION]... PATTERNS [FILE]...`
应该可以在一个命令里面指定多个文件

2024-05-20 11:33 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +# 防止 make deb 打包时运行
1. 注释用英文
2. 这个Makefile直接include下级Makefiles，条件判断在下级里面做

2024-05-21 03:51 UTC, RadxaYuntian requested changes

2024-05-21 03:51 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-can.mak
> +
```suggestion

```

2024-05-21 03:51 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-can.mak
> +endif
```suggestion
endif

```

2024-05-21 07:05 UTC, RadxaYuntian requested changes

2024-05-21 07:05 UTC, RadxaYuntian commented on debian/rules
> +	DEB_VERSION=$(DEB_VERSION) dh_install -X arch/arm64/boot/dts/rockchip/overlays/Makefile.rk3588-can \
只需要把这个Makefile排除就好，dts反正不会编译，最终用户得到的还是同样的结果

2024-05-21 07:05 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +-include arch/arm64/boot/dts/rockchip/overlays/Makefile.rk3588-can
这个我再看看

2024-05-22 08:14 UTC, RadxaYuntian requested changes

2024-05-22 08:14 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	-include $(src)/Makefile.rk3588-can
这个直接放到if外面，Makefile里面本身就相当于对CONFIG_CPU_RK3588做判断
另外测试一下集成到bsp后还会不会编译can overlay

2024-05-22 09:25 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	-include $(src)/Makefile.rk3588-can
![image](https://github.com/radxa-pkg/radxa-overlays/assets/43897062/34cd49d9-4123-49f3-b697-f1df8cd4fe0c)
会的

2024-05-22 10:33 UTC, RadxaYuntian requested changes
squash

2024-05-22 10:33 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	-include $(src)/Makefile.rk3588-can
图片有点问题，我就当可以了

2024-05-23 01:50 UTC, RadxaYuntian approved these changes

2024-05-23 01:52 UTC, merged