add rock 5b otg port1 dts
radxa-pkg/radxa-overlays pull request #328
Opened 2024-06-14 12:01 UTC by vamrs-feng

2024-06-17 04:09 UTC, RadxaYuntian requested changes

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-host.dts
> +		title = "Set OTG port 1 to Host mode (V1.46+, Bottom USB 3.0 port)";
```suggestion
		title = "Set OTG port 1 to Host mode for ROCK 5B V1.46+";
```

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-host.dts
> +		description = "Set OTG port 1 to Host mode.
```suggestion
		description = "Set OTG port 1 to Host mode for ROCK 5B V1.46+.
```

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-host.dts
> +ROCK 5B V1.46+, Bottom USB 3.0 port.
```suggestion
This is the bottom USB 3.0 port.
```

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-host.dts
> +};
```suggestion
};

```

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-peripheral.dts
照上面修改

2024-06-17 04:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-dwc3_1-host.dts
> +		exclusive = "usbdrd_dwc3_1-dr_mode";
```suggestion
```

2024-06-17 12:49 UTC, vamrs-feng reviewed
ok

2024-06-18 02:37 UTC, RadxaYuntian requested changes
你在files changed这个tab里面可以批量选择代码建议，一次性提交
squash一下

2024-06-19 08:14 UTC, RadxaYuntian approved these changes

2024-06-19 08:16 UTC, merged