arm64: rockchip: add rock 5d overlay
radxa-pkg/radxa-overlays pull request #332
Opened 2024-06-20 08:00 UTC by vamrs-feng

2024-06-21 10:39 UTC, RadxaYuntian requested changes
缺少Radxa 8M Camera的overlay

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-okdo-camera-5mp-cam0.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-okdo-camera-5mp-cam0.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-okdo-camera-5mp-cam1.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam0.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam1.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v2-cam0.dts
> +
```suggestion
```

2024-06-21 10:39 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v2-cam1.dts
> +
```suggestion
```

2024-06-24 03:46 UTC, RadxaYuntian requested changes

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-radxa-camera-8mp-cam0.dts
> +
```suggestion
```

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-radxa-camera-8mp-cam0.dts
> +		title ="Enable Raspberry Pi Camera v2 on CAM0";
标题和描述不对

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-radxa-camera-8mp-cam1.dts
> +
```suggestion
```

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-radxa-camera-8mp-cam1.dts
> +		title ="Enable Raspberry Pi Camera v2 on CAM1";
标题和描述不对

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam0.dts
> +		description = "Enable Raspberry Pi Camera v2p3 on CAM0.";
```suggestion
		description = "Enable Raspberry Pi Camera v1.3 on CAM0.";
```

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam0.dts
> +		title ="Enable Raspberry Pi Camera v1p3 on CAM0";
```suggestion
		title ="Enable Raspberry Pi Camera v1.3 on CAM0";
```

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam1.dts
> +		title ="Enable Raspberry Pi Camera v1p3 on CAM1";
```suggestion
		title ="Enable Raspberry Pi Camera v1.3 on CAM1";
```

2024-06-24 03:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5d-rpi-camera-v1p3-cam1.dts
> +		description = "Enable Raspberry Pi Camera v1p3 on CAM1.";
```suggestion
		description = "Enable Raspberry Pi Camera v1.3 on CAM1.";
```

2024-06-25 02:31 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5a-okdo-5mp-camera.dts
> +		compatible = "radxa,rock-5a", "radxa,rock-5c", "radxa,rock-5d";
这怎么后面又有单独的摄像头overlay？

2024-06-25 02:34 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rock-5a-okdo-5mp-camera.dts
> +		compatible = "radxa,rock-5a", "radxa,rock-5c", "radxa,rock-5d";
5D 有三个CSI 接口，包含5A

2024-06-25 02:57 UTC, RadxaYuntian commented
也可以考虑和5AC兼容的那个摄像头单独弄一个overlay来自定义说明和标题，类似[这里](https://github.com/radxa-pkg/radxa-overlays/pull/328/files#diff-1d003be35c642d0f8675af6694381cad360046bc591733dc98e343fa0be3c505)

2024-06-25 03:06 UTC, vamrs-feng commented
> 也可以考虑和5AC兼容的那个摄像头单独弄一个overlay来自定义说明和标题，类似[这里](https://github.com/radxa-pkg/radxa-overlays/pull/328/files#diff-1d003be35c642d0f8675af6694381cad360046bc591733dc98e343fa0be3c505)

这样就

2024-06-25 09:16 UTC, RadxaYuntian requested changes
squash一下

2024-06-26 01:26 UTC, RadxaYuntian approved these changes

2024-06-27 01:25 UTC, merged