fix: resolve all compilation warnings
radxa-pkg/radxa-overlays pull request #338
Opened 2024-06-27 10:02 UTC by CodeChenL

2024-06-27 10:58 UTC, RadxaYuntian requested changes
你拆分一下，按照修复的问题点来，比如把`#address-cells`和`#size-cells`的放到一个提交里

2024-06-27 10:59 UTC, RadxaYuntian commented
另外#address-cells这种确保只给需要加的节点加上了，另外可能还要检查一下base设备树的定义

2024-06-27 11:05 UTC, CodeChenL commented
> 另外#address-cells这种确保只给需要加的节点加上了，另外可能还要检查一下base设备树的定义

回复前半句：我都是一层层往上一级节点加的应该没问题吧？

2024-06-27 11:08 UTC, RadxaYuntian commented
一般上一层加了下一层可能不需要，具体我也不清楚

2024-06-28 01:35 UTC, CodeChenL commented
> 一般上一层加了下一层可能不需要，具体我也不清楚

我有试过去掉下层，但是会恢复报错

2024-06-28 06:22 UTC, RadxaYuntian requested changes
另外提交消息里面最好可以附带上dtc编译时对应的报错信息

2024-06-28 06:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-spi-gpio-enc28j60.dts
> +	#address-cells = <2>;
这个应该是在上一个commit里面

2024-06-28 06:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
> +	interrupt-parent = <&gpio4>;
这个跟下面的interrupts放一起，另外这个看上去是spi的中断，不是gpio的中断？

2024-06-28 06:48 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
> +	interrupt-parent = <&gpio4>;
搜不到pwm的interrupt-parent属性示例

2024-06-28 06:56 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
> +	interrupt-parent = <&gpio4>;
我看pwm1属于gpio4就设置gpio4了

2024-06-28 07:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
> +	interrupt-parent = <&gpio4>;
别人gpio interrupt的对应写法都不一样啊
```
			interrupt-parent = <&gpio2>;
			interrupts = <12 IRQ_TYPE_LEVEL_HIGH>;
``
GIC_SPI中断具体看看主线是怎么定义的

2024-06-28 08:50 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
> +	interrupt-parent = <&gpio4>;
看了一下应该是默认跟随父节点的：https://github.com/radxa/kernel/blob/7a04ba0adee68d9758cbca973b408e9610d229d1/arch/arm64/boot/dts/rockchip/rk3399.dtsi#L22

2024-06-28 09:26 UTC, RadxaYuntian requested changes

2024-06-28 09:26 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/meson-g12-spi-gpio-enc28j60.dts
> -		ranges;
https://devicetree-specification.readthedocs.io/en/latest/chapter2-devicetree-basics.html#ranges
> If the property is defined with an <empty> value, it specifies that the parent and child address space is identical, and no address translation is required.

可能要再确认一下这几个能不能删

2024-06-28 09:26 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dts
>  			panel_in_edp: endpoint {
看看其他指定了endpoint的显示输出是不是port，另外也要实际测试一下

2024-06-28 09:26 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
>  	ethernet: enc28j60@0 {
也可能是这里错了

首先先看看是不是真的要用cs-gpios,看看csn1对应到底哪个引脚，如果没有导出就删了
然后cs-gpios是个数组，元素数目==num-cs,就应该有个<0>来对应spi原生的csn1
确定了cs的配置后才能决定这里到底是cs0还是cs1

2024-06-28 11:07 UTC, CodeChenL commented on arch/arm64/boot/dts/amlogic/overlays/meson-g12-spi-gpio-enc28j60.dts
> -		ranges;
实际测试可以正常驱动enc28j60

2024-07-01 02:46 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dts
>  			panel_in_edp: endpoint {
测试可以正常点亮屏幕，有两种形式有的是posts->post@index, 有的是post

2024-07-01 02:57 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dts
>  			panel_in_edp: endpoint {
这个和跟着驱动来的

2024-07-01 02:58 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dts
>  			panel_in_edp: endpoint {
> 有两种形式有的是posts->post@index

这个哪里有？

2024-07-01 03:48 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-sharp-lq133t1jw01-without-hdmi.dts
>  			panel_in_edp: endpoint {
没事了，是别的屏幕用的驱动是`simple-panel-dsi`

2024-07-01 06:47 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
>  	ethernet: enc28j60@0 {
已修改，并使用硬件enc28j60测试

2024-07-01 06:48 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
> -	pinctrl-0 = <&spi0_csn1 &spi0_pins>;
你这么改有确认过默认的pinctrl里面多出来的引脚定义没有被用到其他地方？

2024-07-01 06:52 UTC, RadxaYuntian requested changes
把提交整理一下，比如那几个interrupt-parent的

2024-07-01 07:14 UTC, RadxaYuntian requested changes
改了直接squash，准备合并了

2024-07-01 07:16 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
>  	num-cs = <2>;
没指定呀，你是不是没看到倒数第二个commit

2024-07-01 07:17 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
>  	num-cs = <2>;
你是说num-cs = <2>;呀，这个需要，不指定会注册spi设备失败

2024-07-01 07:30 UTC, RadxaYuntian approved these changes

2024-07-01 07:31 UTC, merged