rk3588: add i2s1_8ch dummy sound card overlay
radxa-pkg/radxa-overlays pull request #339
Opened 2024-07-02 10:32 UTC by vamrs-feng

2024-07-02 10:35 UTC, RadxaYuntian requested changes

2024-07-02 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +
```suggestion
```

2024-07-02 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +
```suggestion
```

2024-07-02 10:35 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +
```suggestion
```

2024-07-02 10:37 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +		description = "Enable I2S-8CH Dummy Sound Card.";
所以这个接上i2s设备能工作么？

2024-07-02 10:38 UTC, vamrs-feng commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +		description = "Enable I2S-8CH Dummy Sound Card.";
这个不会对应哪个设备，用示波器可以I2S信号就行

2024-07-02 10:41 UTC, RadxaYuntian requested changes

2024-07-02 10:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +		title = "Enable I2S1-8CH Dummy Sound Card";
```suggestion
		title = "Enable I2S1 8-channel dummy sound card";
```

2024-07-02 10:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +		description = "Enable I2S-8CH Dummy Sound Card.";
```suggestion
		description = "Enable I2S1 8-channel dummy sound card.
This overlay is only for demonstration purpose.
It does not support any specific hardware device.";
```

2024-07-02 10:41 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +		exclusive = "GPIO4_A1", "GPIO4_A5", "GPIO4_B0", "GPIO4_B1", "GPIO4_B2", "GPIO4_B3", "GPIO4_B4";
```suggestion
		exclusive = "GPIO4_A1", "GPIO4_A5", "GPIO4_B0", "GPIO4_B1", "GPIO4_B2", "GPIO4_B3", "GPIO4_B4", "i2s1_8ch";
```

2024-07-02 10:49 UTC, RadxaYuntian requested changes
叫sound担心会和以后其他产品的设备树结点名称冲突了

2024-07-02 10:49 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +        dummy_codec: dummy-codec {
```suggestion
        i2s1_dummy_codec: i2s1-dummy-codec {
```

2024-07-02 10:49 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +        sound: sound {
```suggestion
        i2s1_dummy_sound: i2s1-dummy-sound {
```

2024-07-02 10:49 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s1-8ch-m0.dts
> +                                sound-dai = <&dummy_codec>;
```suggestion
                                sound-dai = <&i2s1_dummy_codec>;
```

2024-07-02 10:53 UTC, RadxaYuntian requested changes
squash

2024-07-03 01:42 UTC, RadxaYuntian approved these changes

2024-07-03 01:43 UTC, merged