feat: add w5500 support for rk3568-spi3
radxa-pkg/radxa-overlays pull request #342
Opened 2024-07-05 09:45 UTC by nascs

2024-07-05 10:22 UTC, RadxaYuntian requested changes

2024-07-05 10:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +		title = "Enable W5500 on SPI3-M1 CS GPIO4_D1";
1. 描述说清楚这个W5500是啥
2. 看看enc哪个SPI以太网它的标题和描述是什么格式

2024-07-05 10:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +	max-freq = <50000000>;
```suggestion
```
没有这个属性

2024-07-05 10:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +	eth1: eth1@0 {
```suggestion
	eth_w5500: eth-w5500@0 {
```

2024-07-05 10:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +		mac-address = [00 08 DC 01 02 03];
```suggestion
```
压根就没有这个属性啊：https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/net/wiznet%2Cw5x00.txt#L27
另外我们这里必须定义mac地址么？不能用模块默认地址？

2024-07-05 10:39 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +		mac-address = [00 08 DC 01 02 03];
可以用默认地址，但是这也可以用固定的地址，驱动支持这个属性

2024-07-06 05:07 UTC, RadxaYuntian requested changes

2024-07-06 05:07 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +		title = "Enable W5500 on SPI3-M1 CS0";
```suggestion
		title = "Enable WIZnet W5500 SPI Ethernet controller on SPI3-M1 CS0";
```

2024-07-06 05:07 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-w5500.dts
> +		description = "Enable WIZnet W5500 Ethernet Shield on SPI3-M1 CS0 with.\nINT=22";
```suggestion
		description = "Enable WIZnet W5500 SPI Ethernet controller on SPI3-M1 CS0.
INT=22";
```

2024-07-08 05:47 UTC, RadxaYuntian approved these changes

2024-07-08 05:49 UTC, merged