feat: rk3588: add two i2s2 sound card
radxa-pkg/radxa-overlays pull request #363
Opened 2024-08-26 08:26 UTC by CodeChenL

2024-08-26 08:40 UTC, RadxaYuntian requested changes

2024-08-26 08:40 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		#size-cells = <0>;
缩进

2024-08-26 08:40 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +            };
缩进也不一致

2024-08-26 09:42 UTC, RadxaYuntian requested changes
squash

2024-08-26 09:59 UTC, CodeChenL commented
启用panthor播放音频桌面环境崩溃，我重新刷镜像+重编内核，再排查一下

2024-08-26 10:46 UTC, RadxaYuntian requested changes
和这里的一些输出对比一下:https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

2024-08-26 10:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s2-2ch-m1.dts
> +		compatible = "radxa,rock-5b", "rockchip,rk3588";
如果这里指定了soc就不要指定product

2024-08-26 10:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		compatible = "radxa,rock-5b", "rockchip,rk3588";
如果这里指定了product就不能指定soc

2024-08-26 10:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		title ="Enable HifiBerry DAC";
```suggestion
		title ="Enable HiFiBerry DAC+ Light";
```

2024-08-26 10:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		description = "Enable HifiBerry DAC module as a simple card.";
```suggestion
		description = "Enable HiFiBerry DAC+ Light.";
```

2024-08-26 10:46 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		simple-audio-card,name = "hifiberry dac";
```suggestion
		simple-audio-card,name = "snd_rpi_hifiberry_dac";
```
https://github.com/raspberrypi/linux/blob/rpi-6.6.y/sound/soc/bcm/rpi-simple-soundcard.c#L318

2024-08-26 10:51 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s2-2ch-m1.dts
> +		compatible = "radxa,rock-5b", "rockchip,rk3588";
> 如果这里指定了soc就不要指定product

```suggestion
		compatible = "rockchip,rk3588";
```

2024-08-26 11:09 UTC, CodeChenL commented
> 和这里的一些输出对比一下:https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

![image](https://github.com/user-attachments/assets/d0075161-698b-4bbe-9d6c-89c3c7dee669)
rpi包了一层驱动，稍微不一样

2024-08-27 02:16 UTC, RadxaYuntian requested changes

2024-08-27 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s2-2ch-m1.dts
> +		compatible = "rockchip,rk3588";
如果写soc的话就意味着所有使用这个soc的产品都需要可以开启这个overlay
你确定所有3588产品都在gpio上引出这4个引脚，并且没有使用i2s2_2ch么？

2024-08-27 02:16 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
> +		compatible = "radxa,rock-5b", "rockchip,rk3588";
没有处理

2024-08-28 03:59 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-5b-hifiberry-dac.dts
这个文件我觉得可以叫rk3588-hifi...，因为没有用到特定的GPIO,那就任何有提供I2S2的rk3588产品应该都可以用，最多就是需要自己连接跳线

2024-08-28 10:11 UTC, RadxaYuntian approved these changes

2024-08-28 10:12 UTC, RadxaYuntian requested changes
squash

2024-08-29 02:16 UTC, RadxaYuntian approved these changes

2024-08-29 02:19 UTC, merged