update some overlays for radxa cm5 io
radxa-pkg/radxa-overlays pull request #365
Opened 2024-08-28 05:56 UTC by Ken-Vamrs

2024-08-28 10:07 UTC, RadxaYuntian requested changes

2024-08-28 10:07 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-dwc3-host.dts
include rk3588-dwc3-host.dts然后修改自己专有的部分吧

2024-08-28 10:07 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-rpi-camera-v2.dts
>  	ports {
你整理一下这几个port的关系？感觉嵌套层级不太对

2024-08-28 10:07 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-dwc3-host.dts
> +&vbus5v0_typec {
另外是不是这个的电源定义和其他的产品不一致，或者usb没有指定vbus？为什么别的就不需要额外打开这个regulator

2024-08-28 10:33 UTC, Ken-Vamrs commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-dwc3-host.dts
> +&vbus5v0_typec {
有指定，测试了5b+ 5t也是一样的   只不过他们没有加强制host的overlay，之前cm5 io也是去掉了的，后面说有客户需要就重新加上去了

2024-08-29 02:12 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-dwc3-host.dts
> +Use this when you want to connect USB devices.";
```suggestion
		compatible = "radxa,cm5-io";
```

这几个应该都没变吧

2024-08-29 02:12 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-dwc3-host.dts
> +#include "rk3588-dwc3-host.dts"
```suggestion
#include "rk3588-dwc3-host.dts"
```

2024-08-29 02:12 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-rpi-camera-v2.dts
>  			#address-cells = <1>;
下面的mipidphy0_in_ucam1是endpoint@2不是endpoint@1么？

2024-08-29 02:40 UTC, RadxaYuntian approved these changes
以后pr有修改不要直接改commit后强推，就单独生成一个新commit推上来，这样看得到具体改了哪里，而且github也能自动resolve一些修改意见。待全部结束了再整理提交

2024-08-29 02:43 UTC, merged