feat: add spi1 to rock2
radxa-pkg/radxa-overlays pull request #374
Opened 2024-10-24 12:35 UTC by nascs

2024-10-25 02:22 UTC, RadxaYuntian requested changes

2024-10-25 02:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/Makefile
> +	rk3528-spi1-cs-gpio.dtbo \
```suggestion
	rk3528-spi1-cs-gpio-spidev.dtbo \
```
还有另外两个overlay
可以考虑弄个dtsi

2024-10-25 02:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio.dts
> +		title = "Enable spidev on SPI1 over PIN_26";
```suggestion
		title = "Enable spidev on SPI1";
```
SPI用到4个引脚，怎么over一个引脚
具体格式参考SPI0

2024-10-25 02:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio.dts
> +		description = "Enable spidev on SPI1 over PIN_26.";
```suggestion
		description = "Enable spidev on SPI1.
CS pin is located on pin 26.";
```

2024-10-25 02:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio.dts
> +    pinctrl-0 = <&spi1_pins>;
```suggestion
	cs-gpios = <&gpio4 RK_PC1 GPIO_ACTIVE_LOW>;
	pinctrl-0 = <&spi1_pins>;
```

2024-10-25 02:22 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio.dts
> +	num-cs = <1>;
这个可能不需要，验证一下吧

2024-10-25 02:57 UTC, nascs commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio.dts
> +	num-cs = <1>;
删除 num-cs 可用, 默认应该是 1 个

2024-10-25 03:04 UTC, RadxaYuntian requested changes
不是说了把另外两个overlay也补上么

2024-10-25 03:11 UTC, nascs commented
> 不是说了把另外两个overlay也补上么

enc28j60 和 mcp2515 的?

2024-10-25 03:35 UTC, RadxaYuntian commented
对

2024-10-25 07:30 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/w5500.dtsi
你这没有支持cs-gpios啊

2025-04-01 08:29 UTC, RadxaYuntian requested changes

2025-04-01 08:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio-w5500.dts
> +INT=15";
怎么其他的是36？

2025-04-01 08:29 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3528-spi1-cs-gpio-mcp2515.dts
> +	pinctrl-names = "default";
怎么其他的没有这个属性？

2025-05-28 13:00 UTC, RadxaYuntian commented
？

2026-08-05 09:38 UTC, closed without merging