feat: add rk3568-gpu/hdmi-disable.dts
radxa-pkg/radxa-overlays pull request #377
Opened 2024-11-11 10:08 UTC by CodeChenL

Meets the low-power requirements of some users

2024-11-11 10:11 UTC, RadxaYuntian requested changes
disable-gpu.dts
另外ci应该会报错：makefile没有这两个文件

2024-11-12 02:15 UTC, RadxaYuntian requested changes

2024-11-12 02:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rk3568-hdmi-disable.dts
> +		description = "Disable HDMI";
```suggestion
		description = "Disable HDMI.";
```

2024-11-12 02:15 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rockchip-gpu-disable.dts
> +		description = "Disable GPU";
```suggestion
		description = "Disable GPU.";
```

2024-11-12 05:47 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rockchip-gpu-disable.dts
> +&gpu {
你这个在3588上和mali的overlay互斥吧，有做判断么？

2024-11-12 06:27 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rockchip-gpu-disable.dts
> +&gpu {
rk3588-mali-enable使用了相同的exclusive值 https://github.com/radxa-pkg/radxa-overlays/blob/d24f87e5ef988d457c2db3822940569f38f0039c/arch/arm64/boot/dts/rockchip/overlays/rk3588-mali-enable.dts#L9

2024-11-12 06:40 UTC, RadxaYuntian requested changes
squash

2024-11-19 06:38 UTC, RadxaYuntian approved these changes

2024-11-19 06:40 UTC, merged