Radxa zero 使用 微雪spi 3.5
radxa-pkg/radxa-overlays pull request #380
Opened 2024-11-14 12:46 UTC by YeiliQ

2024-11-15 02:53 UTC, nascs commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-MHS35B-Touch.dts
> +/ {
中间加一个空行

2024-11-15 02:53 UTC, nascs commented
1. 把注释删除, 保持代码简洁
2. title 和 description 可以参考其他的 dts, 如 https://github.com/radxa-pkg/radxa-overlays/blob/449dae0ab1f44a59643d80dbb3ba50930f2ff5c7/arch/arm64/boot/dts/amlogic/overlays/meson-g12-spi-b-enc28j60.dts#L10
3. 在结尾保留一个空行即可

2024-11-15 02:57 UTC, nascs commented on arch/arm64/boot/dts/amlogic/overlays/Makefile
> +	radxa-zero-MHS35B-Touch.dtbo \
radxa-zero-mhs35b.dtbo \

命名风格要和其他保持一致

2024-11-15 06:41 UTC, YeiliQ commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-MHS35B-Touch.dts
> +/ {
已修改

2024-11-15 06:42 UTC, YeiliQ commented
已修改

2024-11-15 06:46 UTC, nascs commented
> 已修改

把修改 push 上来

2024-11-15 07:00 UTC, nascs commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-mhs35b.dts
> +		description = "Enable Waveshare MHS35 on SPI-B and GPIOX_9 GPIOAO_2";
description = "Enable Waveshare MHS35 on SPI-B";

2024-11-15 07:01 UTC, nascs commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-mhs35b.dts
> +
这两个多余空行删一下

2024-11-15 07:02 UTC, nascs commented
我这边没有其他问题了

2024-11-15 07:12 UTC, YeiliQ commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-mhs35b.dts
> +
可以了

2024-11-15 07:32 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-mhs35b.dts
> +		interrupts = <GPIOAO_2 IRQ_TYPE_EDGE_FALLING>;
```suggestion
		interrupts = <2 IRQ_TYPE_EDGE_FALLING>;
```
中断的编号跟GPIO的不一致，所以这里不能用GPIO的常量。你这里可以工作的原因是GPIOAO_2的定义恰巧和中断编号一致，但如果是非AO域的就会出错，所以这里还是显式声明中断号

2024-11-15 07:42 UTC, YeiliQ commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-mhs35b.dts
> +		description = "Enable Waveshare MHS35 on SPI-B";
已修改

2024-11-15 09:09 UTC, RadxaYuntian requested changes

2024-11-15 09:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spi-b-waveshare35b.dts
> +		title = "Enable MHS35B on SPI-B";
```suggestion
		title = "Enable Waveshare 3.5inch RPi LCD (B) on SPI-B";
```

2024-11-15 09:09 UTC, RadxaYuntian commented on arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spi-b-waveshare35b.dts
> +		description = "Enable Waveshare MHS35 on SPI-B";
```suggestion
		description = "Enable Waveshare 3.5inch RPi LCD (B) on SPI-B.";
```

2024-11-15 09:10 UTC, RadxaYuntian approved these changes

2024-11-15 09:10 UTC, RadxaYuntian commented
麻烦squash一下你的提交，合到一起

2024-11-18 05:50 UTC, RadxaYuntian approved these changes

2024-11-18 06:24 UTC, merged