feat: add rock-3ab-max98357a
radxa-pkg/radxa-overlays pull request #387
Opened 2024-12-10 10:06 UTC by CodeChenL

2024-12-10 10:24 UTC, RadxaYuntian requested changes

2024-12-10 10:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +		compatible = "radxa,rock-3a", "radxa,rock-3b";
```suggestion
        compatible = "radxa,rock-3a", "radxa,rock-3b";
```
好多地方缩进都不对

2024-12-10 10:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +		sdmode-gpios = <&gpio3 0 0>;
用常量A0

2024-12-10 10:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +        exclusive = "GPIO3_A0", "GPIO3_A2", "GPIO3_A3", "GPIO3_A4", "GPIO3_A5", "GPIO3_A6", "i2s3_2ch";
看上去设备树只用到了4个I2S和1个SD Mode，这里有6个引脚

2024-12-10 10:24 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +		compatible = "radxa,rock-3a", "radxa,rock-3b";
另外3A也有对应的引脚么？

2024-12-10 10:34 UTC, CodeChenL commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +		compatible = "radxa,rock-3a", "radxa,rock-3b";
有的

2024-12-11 02:11 UTC, RadxaYuntian requested changes

2024-12-11 02:11 UTC, RadxaYuntian commented on arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts
> +        sdmode-gpios = <&gpio3 RK_PA0 0>;
最后的0一般是pull up/down的配置，也有对应的常量

2024-12-11 02:23 UTC, RadxaYuntian requested changes
squash

2024-12-11 02:34 UTC, RadxaYuntian approved these changes

2024-12-11 02:37 UTC, merged